#!/usr/bin/env python
"""Writes final_outputs/README.md from figure_data/ artifacts rather than hand-typed values.

Invoked by make final-outputs. Every quantity in the generated README is sourced from
figure_data/, so the manifest cannot drift from what was packaged.
"""
import csv
import hashlib
import json
import os
import platform
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
SUB = os.path.join(ROOT, "final_outputs")
FIGDATA = os.path.join(ROOT, "figure_data")

# The platform statement is defined once, in the table packager.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from package_supplementary_tables import PLATFORM_STATEMENT  # noqa: E402


def sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 16), b""):
            h.update(chunk)
    return h.hexdigest()


def supplementary_figures():
    """Reuses the packager's TSV parser, so the README cannot disagree with what final-outputs copied."""
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    import package_supplementary_figures as psf

    rows = psf.read_manifest()
    psf.validate(rows)
    return sorted(rows, key=lambda r: r["number"])


def listing(subdir):
    """Every file under subdir, recursively, as (path relative to subdir, size, sha256).

    Recursive because each figure directory has a pdf/ subdirectory beside the PNGs; a flat
    os.listdir would hash the PNGs and silently omit the vector deliverable next to them.
    """
    d = os.path.join(SUB, subdir)
    out = []
    for dirpath, _, names in os.walk(d):
        for name in names:
            if name == ".DS_Store":       # Finder debris, not a deliverable; excluded tree-wide
                continue
            p = os.path.join(dirpath, name)
            if os.path.isfile(p):
                out.append((os.path.relpath(p, d), os.path.getsize(p), sha256(p)))
    return sorted(out)


# Uses a real CSV reader, not comma-splitting: the quoted label column spans two physical lines.
ladder = {}
with open(os.path.join(FIGDATA, "panelA_auc_ladder.csv"), newline="") as fh:
    for row in csv.DictReader(fh):
        ladder[row["model"]] = float(row["auc"])

# Fails loudly rather than emit a manifest missing its headline number.
for _needed in ("genetic only", "full"):
    if _needed not in ladder:
        raise SystemExit(
            f"panelA_auc_ladder.csv has no '{_needed}' row; got {sorted(ladder)}. "
            "Refusing to write a submission manifest without the headline AUC.")

heldout = json.load(open(os.path.join(FIGDATA, "heldout_trial_auc.json")))

# Figure S2's caveats were hand-typed and drifted from the data when the feature matrix
# changed; every quantity below is read instead. Only tracked files are used, since
# make final-outputs must run on a clean clone.
_disc = json.load(open(os.path.join(FIGDATA, "discordance_stats.json")))
_n_marked = _disc["n_core_promoted"] + _disc["n_core_demoted"]
with open(os.path.join(FIGDATA, "discordance_core_genes.csv"), newline="") as fh:
    _cuts = (_disc["lo_cut"], _disc["hi_cut"])
    _near = sum(1 for r in csv.DictReader(fh)
                if min(abs(float(r[c]) - k)
                       for c in ("pctile_genetics", "pctile_full") for k in _cuts) < 0.01)

lines = []
lines.append("# Submission package — computational display items")
lines.append("")
lines.append("Generated by `make final-outputs` from the verified `final_plots/`. On Apple Silicon")
lines.append("macOS every figure here is byte-reproducible from this repository: `make figures` rebuilds them from")
lines.append("committed tables in about 20 seconds with no model fitting, and `make verify`")
lines.append("checks them against committed checksums.")
lines.append("")
lines.append("This package contains **only display items**.")
lines.append("")
lines.append(PLATFORM_STATEMENT)
lines.append("")
if not (platform.system() == "Darwin" and platform.machine() == "arm64"):
    lines.append(f"> **This package was built on {platform.system()} {platform.machine()}, not macOS "
                 "(Apple Silicon).** Minor")
    lines.append("> numerical differences from the reported values are expected, as described above.")
    lines.append("> See REPRODUCIBILITY.md, Cross-platform reproduction.")
    lines.append("")
lines.append("## Main figures")
lines.append("")
lines.append("Renamed to the manuscript's figure numbers. Source names are given so each maps")
lines.append("back to the script that produced it.")
lines.append("")
lines.append("| Packaged as | Source file in `final_plots/` |")
lines.append("|---|---|")
for packaged, source in [
    ("Fig2_genetic_data.png", "genetic_data.png"),
    ("Fig2_genetic_data.pdf", "pdf/genetic_data.pdf"),
    ("Fig3_perturbational_functional_genomics.png", "perturbational_functional_genomics_with_thde.png"),
    ("Fig3_perturbational_functional_genomics.pdf", "pdf/perturbational_functional_genomics_with_thde.pdf"),
    ("Fig4_model_analysis.png", "figure_model_analysis_composite.png"),
    ("Fig4_model_analysis.pdf", "pdf/figure_model_analysis_composite.pdf"),
    ("Fig5_trial_validation.png", "figure_trial_validation_immune_stages_R.png"),
    ("Fig5_trial_validation.pdf", "pdf/figure_trial_validation_immune_stages_R.pdf"),
    ("Fig6_prospective_temporal_holdout.png", "figure_prospective_temporal_holdout.png"),
    ("Fig6_prospective_temporal_holdout.pdf", "pdf/figure_prospective_temporal_holdout.pdf"),
    ("Fig7_specificity_control.png", "specificity_immune_vs_cardiac_faceted.png"),
    ("Fig7_specificity_control.pdf", "pdf/specificity_immune_vs_cardiac_faceted.pdf"),
    ("Fig8_stat4_vignette.png", "figure_stat4_vignette.png"),
    ("Fig8_stat4_vignette.pdf", "pdf/figure_stat4_vignette.pdf"),
]:
    sub = "main_figures/pdf" if packaged.endswith(".pdf") else "main_figures"
    # PDFs are rendered only on macOS; list only what was actually packaged.
    if not os.path.isfile(os.path.join(SUB, sub, packaged)):
        continue
    lines.append(f"| `{sub}/{packaged}` | `{source}` |")
lines.append("")
lines.append("## Headline numbers, read from the packaged data")
lines.append("")
lines.append("Two different AUCs appear in this work and they are not interchangeable:")
lines.append("")
gen = ladder["genetic only"]
full = ladder["full"]
lines.append(f"- **Cross-validated ROC-AUC, full model: {full:.4f}** "
             "(approved vs unlabeled, 5-fold × 5 seeds)")
lines.append(f"- Cross-validated ROC-AUC, genetic priors only: {gen:.4f}")
lines.append(f"- **Held-out in-trial ROC-AUC, full model: {heldout['auc_full']:.4f}** "
             f"({heldout['n_in_trial']:,} in-trial vs {heldout['n_non_target']:,} non-target genes)")
lines.append(f"- Held-out in-trial ROC-AUC, genetics only: {heldout['auc_genetics']:.4f} "
             f"(Δ {heldout['delta']:+.4f}, paired DeLong p = {heldout['delong_p']:.3f})")
lines.append("")
lines.append("The cross-validated AUC is deflated by construction — unlabeled genes are scored")
lines.append("as negatives when an unknown number are undiscovered targets — and is intended for")
lines.append("model comparison, not as an absolute performance claim.")
lines.append("")
lines.append("## Supplementary figures")
lines.append("")
lines.append("| Packaged as | Source file |")
lines.append("|---|---|")
# Reads the mapping from tools/supplementary_figures.tsv, the single source of truth, preventing drift.
for figure in supplementary_figures():
    lines.append(f"| `supplementary_figures/{figure['submission_name']}` "
                 f"| `{figure['source']}` |")
    # Derives the source path as package_supplementary_figures.pdf_source() does, so it matches what was copied.
    stem = figure["submission_name"].rsplit(".", 1)[0]
    src_stem = figure["source"].rsplit("/", 1)[-1].rsplit(".", 1)[0]
    if os.path.isfile(os.path.join(SUB, "supplementary_figures", "pdf", f"{stem}.pdf")):
        lines.append(f"| `supplementary_figures/pdf/{stem}.pdf` | `pdf/{src_stem}.pdf` |")
lines.append("")
if not os.path.isdir(os.path.join(SUB, "main_figures", "pdf")):
    lines.append("> **No PDFs in this package.** They are rendered only on macOS, whose quartz")
    lines.append("> device writes them; every PNG, table and number above is unaffected.")
    lines.append("")
lines.append("> **S3** is produced by `build_leakage_controlled.py` → `fig_leakage_controlled.R`,")
lines.append("> with a paired DeLong on the shared 535-positive set (ΔAUC = +0.053, z = 3.62,")
lines.append("> p = 2.9e-4). AUCs at 24 features: 0.636 standard / 0.645 leakage-controlled.")
lines.append("> Provenance: `figure_data/PROVENANCE.md` in the code repository.")
lines.append("")
# This caveat names the held-out in-trial AUC value directly: it has no figure number, though reported above.
lines.append("> **The held-out in-trial AUC reported above is an in-trial AUC** and must never be")
lines.append("> presented as a drop from the headline cross-validated figure. Different label")
lines.append("> sets, different tasks. It is no longer a numbered supplementary figure; the ROC")
lines.append("> curves and discrimination statistics ship as Supplementary Table 7.")
lines.append("")
lines.append("> **S2 answers \"the increment is made of what?\"** -- the question the magnitude")
lines.append("> arguments in the AUC beat leave open. One thing must travel with it: the "
             "%d" % _n_marked)
lines.append("> marked genes are a **single-seed set**: %d of them sit within 0.01 of a quadrant cut,"
             % _near)
lines.append("> so quote them as \"genes the production model ranks oppositely to a genetics-only")
lines.append("> model\", never as reseed-stable. The aggregate statistics")
lines.append("> (rho = %.3f over %s genes; the driver axis; Mantel-Haenszel p = %.1e) are computed"
             % (_disc["spearman_arms"], f"{_disc['n_genes']:,}", _disc["mh_p"]))
lines.append("> on thousands of genes and are not seed-fragile.")
lines.append("")
lines.append("> **S2's STRING/GO tables are cached inputs, not rebuilt by `make tables`.** They come")
lines.append("> from the opt-in `make discordance-network` target, which reads ~135 MB of external")
lines.append("> archives that are deliberately not committed. `make verify-tables` proves they have")
lines.append("> not changed, not that they re-derive. See `figure_data/PROVENANCE.md`.")
lines.append("")
# Renderer script names are omitted.
# One checksum table over every packaged file, main figures included. The sections above say
# where each file came from; this one is the integrity record. final_outputs/ is gitignored, so
# a packaged file with no row here has no recovery path at all.
lines.append("## Checksums")
lines.append("")
if os.path.isdir(os.path.join(SUB, "main_figures", "pdf")):
    lines.append("Every file in this package. `.pdf` rows change on each render -- the R PDF device")
    lines.append("stamps a wall-clock creation date -- so they record what was shipped rather than a")
    lines.append("reproduction claim; `tools/compare_submission.py` normalises them before comparing.")
else:
    lines.append("Every file in this package.")
lines.append("")
lines.append("| File | Bytes | SHA-256 (first 16) |")
lines.append("|---|---:|---|")
for sub in ("main_figures", "supplementary_figures", "supplementary_tables"):
    for name, size, digest in listing(sub):
        lines.append(f"| `{sub}/{name}` | {size:,} | `{digest[:16]}` |")
lines.append("")
lines.append("## Not included, and why")
lines.append("")
# Renderer script names are omitted.
lines.append("- **The held-out in-trial AUC figure** — not a numbered display item. Its statistics")
lines.append("  ship as the ROC and discrimination sheets of Supplementary Table 7, and in `figure_data/`.")
lines.append("- **`supplementary_data/`** — not included. Every table it used to carry is a")
lines.append("  sheet of a numbered supplementary table, sourced from `figure_data/`.")
lines.append("- Per-figure provenance and sample sizes — these live in the \"Reading the")
lines.append("  figures\" section of the repository README, not as a packaged file. Add a")
lines.append("  copy if the journal asks for per-panel counts.")
lines.append("")

os.makedirs(SUB, exist_ok=True)
with open(os.path.join(SUB, "README.md"), "w") as fh:
    fh.write("\n".join(lines) + "\n")
print("wrote final_outputs/README.md")
